# This file is generated by generate_cmake.sh
# NIP options
option(ENABLE_NIP01 "Enable nip01" OFF)
if(ENABLE_NIP01)
    add_subdirectory(nips/nip01)
endif()

option(ENABLE_NIP02 "Enable nip02" OFF)
if(ENABLE_NIP02)
    add_subdirectory(nips/nip02)
endif()

option(ENABLE_NIP04 "Enable nip04" ON)
if(ENABLE_NIP04)
    add_subdirectory(nips/nip04)
endif()

option(ENABLE_NIP05 "Enable nip05" ON)
if(ENABLE_NIP05)
    add_subdirectory(nips/nip05)
endif()

option(ENABLE_NIP06 "Enable nip06" ON)
if(ENABLE_NIP06)
    add_subdirectory(nips/nip06)
endif()

option(ENABLE_NIP10 "Enable nip10" OFF)
if(ENABLE_NIP10)
    add_subdirectory(nips/nip10)
endif()

option(ENABLE_NIP11 "Enable nip11" OFF)
if(ENABLE_NIP11)
    add_subdirectory(nips/nip11)
endif()

option(ENABLE_NIP13 "Enable nip13" OFF)
if(ENABLE_NIP13)
    add_subdirectory(nips/nip13)
endif()

option(ENABLE_NIP19 "Enable nip19" ON)
if(ENABLE_NIP19)
    add_subdirectory(nips/nip19)
endif()

option(ENABLE_NIP29 "Enable nip29" OFF)
if(ENABLE_NIP29)
    add_subdirectory(nips/nip29)
endif()

option(ENABLE_NIP31 "Enable nip31" OFF)
if(ENABLE_NIP31)
    add_subdirectory(nips/nip31)
endif()

option(ENABLE_NIP34 "Enable nip34" OFF)
if(ENABLE_NIP34)
    add_subdirectory(nips/nip34)
endif()

option(ENABLE_NIP42 "Enable nip42" OFF)
if(ENABLE_NIP42)
    add_subdirectory(nips/nip42)
endif()

option(ENABLE_NIP44 "Enable nip44" ON)
if(ENABLE_NIP44)
    add_subdirectory(nips/nip44)
endif()

# Ensure nip46's link-time dependency on nostr_nip44_core is satisfied
if(ENABLE_NIP46)
    set(ENABLE_NIP44 ON CACHE BOOL "Enable nip44" FORCE)
endif()

option(ENABLE_NIP46 "Enable nip46" ON)
if(ENABLE_NIP46)
    add_subdirectory(nips/nip46)
endif()

option(ENABLE_NIP47 "Enable nip47" ON)
if(ENABLE_NIP47)
    add_subdirectory(nips/nip47)
endif()

option(ENABLE_NIP48 "Enable nip48" OFF)
if(ENABLE_NIP48)
    add_subdirectory(nips/nip48)
endif()

option(ENABLE_NIP49 "Enable nip49" ON)
if(ENABLE_NIP49)
    add_subdirectory(nips/nip49)
endif()

option(ENABLE_NIP52 "Enable nip52" OFF)
if(ENABLE_NIP52)
    add_subdirectory(nips/nip52)
endif()

option(ENABLE_NIP53 "Enable nip53" OFF)
if(ENABLE_NIP53)
    add_subdirectory(nips/nip53)
endif()

option(ENABLE_NIP54 "Enable nip54" OFF)
if(ENABLE_NIP54)
    add_subdirectory(nips/nip54)
endif()

option(ENABLE_NIP5F "Enable nip5f" ON)
if(ENABLE_NIP5F)
    add_subdirectory(nips/nip5f)
endif()

option(ENABLE_NIP94 "Enable nip94" OFF)
if(ENABLE_NIP94)
    add_subdirectory(nips/nip94)
endif()

# DBus signer (nip55l)
option(ENABLE_NIP55L "Enable nip55l" ON)
if(ENABLE_NIP55L)
    add_subdirectory(nips/nip55l)
endif()


# NIP-77 Negentropy (optional module)
option(WITH_NIP77 "Build NIP-77 (Negentropy) optional module" ON)
option(WITH_NIP77_GLIB "Build GLib wrapper for NIP-77" OFF)
option(WITH_NIP77_NOSTRDB "Enable nostrdb backend for NIP-77" ON)
if(WITH_NIP77)
    add_subdirectory(nips/nip77)
endif()

