# This file is generated by generate_cmake.sh
# NIP options
option(ENABLE_NIP01 "Enable nip01" OFF)
if(ENABLE_NIP01)
    add_subdirectory(nips/nip01)
endif()

option(ENABLE_NIP02 "Enable nip02" OFF)
if(ENABLE_NIP02)
    add_subdirectory(nips/nip02)
endif()

option(ENABLE_NIP04 "Enable nip04" ON)
if(ENABLE_NIP04)
    add_subdirectory(nips/nip04)
endif()

option(ENABLE_NIP05 "Enable nip05" ON)
if(ENABLE_NIP05)
    add_subdirectory(nips/nip05)
endif()

option(ENABLE_NIP06 "Enable nip06" ON)
if(ENABLE_NIP06)
    add_subdirectory(nips/nip06)
endif()

option(ENABLE_NIP10 "Enable nip10" OFF)
if(ENABLE_NIP10)
    add_subdirectory(nips/nip10)
endif()

option(ENABLE_NIP11 "Enable nip11" ON)
if(ENABLE_NIP11)
    add_subdirectory(nips/nip11)
endif()

# NIP-17 depends on NIP-44 for encryption
if(ENABLE_NIP17)
    set(ENABLE_NIP44 ON CACHE BOOL "Enable nip44" FORCE)
endif()

option(ENABLE_NIP17 "Enable nip17 (Private Direct Messages)" ON)
if(ENABLE_NIP17)
    add_subdirectory(nips/nip17)
endif()

# NIP-59 depends on NIP-44 for encryption
if(ENABLE_NIP59)
    set(ENABLE_NIP44 ON CACHE BOOL "Enable nip44" FORCE)
endif()

option(ENABLE_NIP59 "Enable nip59 (Gift Wrap)" ON)
if(ENABLE_NIP59)
    add_subdirectory(nips/nip59)
endif()

option(ENABLE_NIP13 "Enable nip13" OFF)
if(ENABLE_NIP13)
    add_subdirectory(nips/nip13)
endif()

option(ENABLE_NIP14 "Enable nip14 (Subject Tag)" ON)
if(ENABLE_NIP14)
    add_subdirectory(nips/nip14)
endif()

option(ENABLE_NIP19 "Enable nip19" ON)
if(ENABLE_NIP19)
    add_subdirectory(nips/nip19)
endif()

# NIP-21 depends on NIP-19 for bech32 encoding/decoding
if(ENABLE_NIP21)
    set(ENABLE_NIP19 ON CACHE BOOL "Enable nip19" FORCE)
endif()

option(ENABLE_NIP21 "Enable nip21 (nostr: URI Scheme)" ON)
if(ENABLE_NIP21)
    add_subdirectory(nips/nip21)
endif()

# NIP-27 depends on NIP-21 (and transitively NIP-19) for URI parsing
if(ENABLE_NIP27)
    set(ENABLE_NIP21 ON CACHE BOOL "Enable nip21" FORCE)
endif()

option(ENABLE_NIP27 "Enable nip27 (Text Note References)" ON)
if(ENABLE_NIP27)
    add_subdirectory(nips/nip27)
endif()

option(ENABLE_NIP23 "Enable nip23 (Long-form Content)" ON)
if(ENABLE_NIP23)
    add_subdirectory(nips/nip23)
endif()

option(ENABLE_NIP22 "Enable nip22 (Comments)" ON)
if(ENABLE_NIP22)
    add_subdirectory(nips/nip22)
endif()

option(ENABLE_NIP28 "Enable nip28 (Public Chat)" ON)
if(ENABLE_NIP28)
    add_subdirectory(nips/nip28)
endif()

option(ENABLE_NIP24 "Enable nip24 (Extra Metadata)" ON)
if(ENABLE_NIP24)
    add_subdirectory(nips/nip24)
endif()

option(ENABLE_NIP25 "Enable nip25 (Reactions)" ON)
if(ENABLE_NIP25)
    add_subdirectory(nips/nip25)
endif()

option(ENABLE_NIP30 "Enable nip30 (Custom Emoji)" ON)
if(ENABLE_NIP30)
    add_subdirectory(nips/nip30)
endif()

option(ENABLE_NIP29 "Enable nip29" OFF)
if(ENABLE_NIP29)
    add_subdirectory(nips/nip29)
endif()

option(ENABLE_NIP31 "Enable nip31" OFF)
if(ENABLE_NIP31)
    add_subdirectory(nips/nip31)
endif()

option(ENABLE_NIP34 "Enable nip34" OFF)
if(ENABLE_NIP34)
    add_subdirectory(nips/nip34)
endif()

option(ENABLE_NIP39 "Enable nip39 (External Identities)" ON)
if(ENABLE_NIP39)
    add_subdirectory(nips/nip39)
endif()

option(ENABLE_NIP40 "Enable nip40 (Expiration)" ON)
if(ENABLE_NIP40)
    add_subdirectory(nips/nip40)
endif()

option(ENABLE_NIP42 "Enable nip42" OFF)
if(ENABLE_NIP42)
    add_subdirectory(nips/nip42)
endif()

option(ENABLE_NIP45 "Enable nip45" ON)
if(ENABLE_NIP45)
    add_subdirectory(nips/nip45)
endif()

option(ENABLE_NIP44 "Enable nip44" ON)
if(ENABLE_NIP44)
    add_subdirectory(nips/nip44)
endif()

# Ensure nip46's link-time dependency on nostr_nip44_core is satisfied
if(ENABLE_NIP46)
    set(ENABLE_NIP44 ON CACHE BOOL "Enable nip44" FORCE)
endif()

option(ENABLE_NIP46 "Enable nip46" ON)
if(ENABLE_NIP46)
    add_subdirectory(nips/nip46)
endif()

option(ENABLE_NIP47 "Enable nip47" ON)
if(ENABLE_NIP47)
    add_subdirectory(nips/nip47)
endif()

option(ENABLE_NIP48 "Enable nip48" OFF)
if(ENABLE_NIP48)
    add_subdirectory(nips/nip48)
endif()

option(ENABLE_NIP49 "Enable nip49" ON)
if(ENABLE_NIP49)
    add_subdirectory(nips/nip49)
endif()

option(ENABLE_NIP52 "Enable nip52" OFF)
if(ENABLE_NIP52)
    add_subdirectory(nips/nip52)
endif()

option(ENABLE_NIP53 "Enable nip53" OFF)
if(ENABLE_NIP53)
    add_subdirectory(nips/nip53)
endif()

option(ENABLE_NIP86 "Enable nip86 (Relay Management API)" ON)
if(ENABLE_NIP86)
    add_subdirectory(nips/nip86)
endif()

option(ENABLE_NIP54 "Enable nip54" OFF)
if(ENABLE_NIP54)
    add_subdirectory(nips/nip54)
endif()

# NIP-57 Lightning Zaps
option(ENABLE_NIP57 "Enable nip57 (Lightning Zaps)" ON)
if(ENABLE_NIP57)
    add_subdirectory(nips/nip57)
endif()

option(ENABLE_NIP58 "Enable nip58 (Badges)" ON)
if(ENABLE_NIP58)
    add_subdirectory(nips/nip58)
endif()

option(ENABLE_NIP60 "Enable nip60 (Cashu Wallet)" ON)
if(ENABLE_NIP60)
    add_subdirectory(nips/nip60)
endif()

option(ENABLE_NIP61 "Enable nip61 (Nutzaps)" ON)
if(ENABLE_NIP61)
    add_subdirectory(nips/nip61)
endif()

option(ENABLE_NIP70 "Enable nip70 (Protected Events)" ON)
if(ENABLE_NIP70)
    add_subdirectory(nips/nip70)
endif()

option(ENABLE_NIP75 "Enable nip75 (Zap Goals)" ON)
if(ENABLE_NIP75)
    add_subdirectory(nips/nip75)
endif()

option(ENABLE_NIP73 "Enable nip73 (External Content IDs)" ON)
if(ENABLE_NIP73)
    add_subdirectory(nips/nip73)
endif()

option(ENABLE_NIP5F "Enable nip5f" ON)
if(ENABLE_NIP5F)
    add_subdirectory(nips/nip5f)
endif()

option(ENABLE_NIP99 "Enable nip99 (Classified Listings)" ON)
if(ENABLE_NIP99)
    add_subdirectory(nips/nip99)
endif()

option(ENABLE_NIP92 "Enable nip92 (Image Metadata)" ON)
if(ENABLE_NIP92)
    add_subdirectory(nips/nip92)
endif()

option(ENABLE_NIP94 "Enable nip94" OFF)
if(ENABLE_NIP94)
    add_subdirectory(nips/nip94)
endif()

# DBus signer (nip55l)
# Always add nip55l — the core library is needed by gnostr-signer on all
# platforms; only the GLib/DBus layer is conditionally built inside the
# subdirectory based on GIO availability.
option(ENABLE_NIP55L "Enable nip55l GLib/DBus layer" ON)
add_subdirectory(nips/nip55l)


# NIP-77 Negentropy (optional module)
option(WITH_NIP77 "Build NIP-77 (Negentropy) optional module" ON)
option(WITH_NIP77_GLIB "Build GLib wrapper for NIP-77" OFF)
option(WITH_NIP77_NOSTRDB "Enable nostrdb backend for NIP-77" ON)
if(WITH_NIP77)
    add_subdirectory(nips/nip77)
endif()

# NIP-50 Search (optional)
option(ENABLE_NIP50 "Enable nip50 (Search)" ON)
if(ENABLE_NIP50)
    add_subdirectory(nips/nip50)
endif()

# NIP-51 depends on NIP-44 for private entry encryption
if(ENABLE_NIP51)
    set(ENABLE_NIP44 ON CACHE BOOL "Enable nip44" FORCE)
endif()

option(ENABLE_NIP51 "Enable nip51 (User Lists)" ON)
if(ENABLE_NIP51)
    add_subdirectory(nips/nip51)
endif()

# Event Schema Validation
option(ENABLE_SCHEMA "Enable schema (Event Schema Validation)" ON)
if(ENABLE_SCHEMA)
    add_subdirectory(nips/schema)
endif()

# NIP-98 HTTP Auth (used by NIP-96 file storage and Blossom)
option(ENABLE_NIP98 "Enable nip98 (HTTP Auth)" ON)
if(ENABLE_NIP98)
    add_subdirectory(nips/nip98)
endif()

# Blossom (NIP-B0): Blob Storage Protocol
option(ENABLE_NIPB0 "Enable nipb0 (Blossom Client Protocol)" ON)
if(ENABLE_NIPB0)
    add_subdirectory(nips/nipb0)
endif()

