#ifndef GNOSTR_SIGNER_IPC_H
#define GNOSTR_SIGNER_IPC_H

#include <gio/gio.h>
#include "signer_proxy.h"  /* generated by gdbus-codegen */

G_BEGIN_DECLS

/* Use the exact generated proxy type */
typedef NostrOrgNostrSigner NostrSignerProxy;

/* Initialize and acquire a shared proxy. Returns NULL on failure. */
NostrSignerProxy *gnostr_signer_proxy_get(GError **error);

/* Clear cached failure state so next get() retries D-Bus.
 * Call after NIP-46 login or when signer service becomes available. */
void gnostr_signer_proxy_reset(void);

/* Release shared proxy (called at app shutdown). */
void gnostr_signer_proxy_shutdown(void);

G_END_DECLS

#endif /* GNOSTR_SIGNER_IPC_H */
