#include "signer_ipc.h"
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>

/* Generated by gdbus-codegen (see apps/gnostr/CMakeLists.txt) */
#include "signer_proxy.h"

static NostrSignerProxy *g_shared_proxy = NULL;

NostrSignerProxy *gnostr_signer_proxy_get(GError **error) {
  if (g_shared_proxy) return g_shared_proxy;
  /* Fail-fast: acquire proxy on session bus at canonical path */
  g_shared_proxy = nostr_org_nostr_signer_proxy_new_for_bus_sync(
      G_BUS_TYPE_SESSION,
      G_DBUS_PROXY_FLAGS_NONE,
      "org.nostr.Signer",
      "/org/nostr/signer",
      NULL, /* GCancellable */
      error);
  if (!g_shared_proxy) {
    /* error already set by GLib */
    return NULL;
  }
  return g_shared_proxy;
}

void gnostr_signer_proxy_shutdown(void) {
  if (g_shared_proxy) {
    g_clear_object(&g_shared_proxy);
  }
}
