#ifndef GH_RELAY_AUTH_H
#define GH_RELAY_AUTH_H

#include <gio/gio.h>

G_BEGIN_DECLS

/*
 * NIP-42 client authentication for Groundhog relay scopes and publishes.
 *
 * AUTH identity policy (privacy charter §4.4). Which identity, if any,
 * authenticates a connection is an explicit per-URL choice of the caller,
 * never a global or automatic one:
 *
 *  - GH_RELAY_AUTH_NONE (the default for every URL): nothing is signed; the
 *    relay's CLOSED / OK "auth-required:" is the outcome.
 *  - GH_RELAY_AUTH_EPHEMERAL: a fresh throwaway keypair is generated by this
 *    relay layer for each AUTH (at most one per connection), the event is
 *    signed with it, and the secret is wiped immediately. It is never reused
 *    for another connection or URL and is never the account key. Use it for
 *    connections that must not be linked to the account, e.g. writing a
 *    gift wrap to a recipient's inbox relay, discovery, MLS routing.
 *  - GH_RELAY_AUTH_ACCOUNT: the caller-supplied, generation-bound account
 *    signer (GhRelayAuthSigner). Only for the account's own inbox and list
 *    relays and NIP-29 group relays. AUTH as the account on a recipient's
 *    inbox relay would tie the sender to the gift wrap and undo NIP-59's
 *    ephemeral outer key.
 *
 * There is no escalation: a relay that refuses an ephemeral AUTH ends as
 * CLOSED / AUTH_REQUIRED; Groundhog never retries as the account.
 *
 * A GhRelayAuthSigner is the caller-supplied hook that turns an unsigned
 * kind-22242 event into a signed one, asynchronously. It is bound to ONE
 * account generation: a scope or publish only accepts a signer of its own
 * generation, and a revoked signer (gh_relay_auth_signer_revoke(), or the
 * optional generation cancellable being cancelled) never signs again, cancels
 * the sign operations in flight and fails the AUTH attempts they belong to.
 *
 * Groundhog builds the event itself (["relay", <url>], ["challenge", <c>],
 * current created_at, empty content), and verifies the signed result before
 * it is sent: valid id and signature, kind 22242, the same relay and
 * challenge tags, created_at within GH_RELAY_AUTH_MAX_SKEW_SECONDS and, when
 * the signer names one, the expected pubkey. Anything else is rejected
 * locally and never reaches the relay.
 *
 * AUTH is lazy: a challenge alone is only recorded. Groundhog authenticates
 * once the relay refuses a REQ (CLOSED "auth-required:") or an EVENT
 * (OK false "auth-required:") on a connection that has sent a challenge, at
 * most once per challenge, and retries that REQ/EVENT once after the relay's
 * OK true for the AUTH event.
 */

#define GH_RELAY_AUTH_KIND 22242
#define GH_RELAY_AUTH_MAX_SKEW_SECONDS 600

typedef enum {
  GH_RELAY_AUTH_NONE = 0,
  GH_RELAY_AUTH_EPHEMERAL,
  GH_RELAY_AUTH_ACCOUNT
} GhRelayAuthMode;

typedef struct _GhRelayAuthSigner GhRelayAuthSigner;

/* Signs @unsigned_event_json (a NIP-01 event without id/sig; pubkey present
 * only when the signer was given an expected pubkey) and completes on the
 * thread-default main context that was current when it was called, like any
 * GIO async function. @cancellable is cancelled when the attempt is dropped
 * (scope/publish cancelled, connection lost, signer revoked). The shape
 * matches gh_account_controller_sign_with_cancellable_async() with the
 * controller as @user_data. */
typedef void (*GhRelayAuthSignAsyncFunc)(gpointer user_data,
                                         const gchar *unsigned_event_json,
                                         GCancellable *cancellable,
                                         GAsyncReadyCallback callback,
                                         gpointer callback_data);
/* Returns the signed event JSON (transfer full), or NULL with @error set
 * (e.g. the user or signer refused). Matches gh_account_controller_sign_finish(). */
typedef gchar *(*GhRelayAuthSignFinishFunc)(GAsyncResult *result,
                                            GError **error);

/* @generation_cancellable (nullable) revokes the signer when cancelled; pass
 * the account controller's generation cancellable. @expected_pubkey
 * (nullable, 64 hex) is put in the template and required of the result. */
GhRelayAuthSigner *gh_relay_auth_signer_new(guint64 account_generation,
                                            GCancellable *generation_cancellable,
                                            const gchar *expected_pubkey,
                                            GhRelayAuthSignAsyncFunc sign_async,
                                            GhRelayAuthSignFinishFunc sign_finish,
                                            gpointer user_data,
                                            GDestroyNotify user_data_destroy);
GhRelayAuthSigner *gh_relay_auth_signer_ref(GhRelayAuthSigner *signer);
void gh_relay_auth_signer_unref(GhRelayAuthSigner *signer);
void gh_relay_auth_signer_revoke(GhRelayAuthSigner *signer);
gboolean gh_relay_auth_signer_is_revoked(const GhRelayAuthSigner *signer);
guint64 gh_relay_auth_signer_get_generation(const GhRelayAuthSigner *signer);

G_DEFINE_AUTOPTR_CLEANUP_FUNC(GhRelayAuthSigner, gh_relay_auth_signer_unref)

/* NIP-01 "auth-required:" machine-readable prefix (CLOSED and OK). */
gboolean gh_relay_auth_is_required(const gchar *message);

/* A kind-22242 event for (@relay_url, @challenge) signed with a freshly
 * generated keypair whose secret is wiped before this returns. Every call
 * uses a new key. */
gchar *gh_relay_auth_sign_ephemeral(const gchar *relay_url, const gchar *challenge,
                                    gint64 created_at, GError **error);

/* The unsigned kind-22242 template; @pubkey is nullable. */
gchar *gh_relay_auth_build_unsigned(const gchar *relay_url, const gchar *challenge,
                                    const gchar *pubkey, gint64 created_at);
/* Local check of a signed AUTH event against what was asked for; fills
 * @event_id (65 bytes) on success, G_IO_ERROR_INVALID_DATA otherwise. */
gboolean gh_relay_auth_verify_signed(const gchar *signed_json,
                                     const gchar *relay_url,
                                     const gchar *challenge,
                                     const gchar *expected_pubkey,
                                     gint64 now,
                                     gchar *event_id,
                                     GError **error);

/* Internal: one sign-and-verify attempt for one (URL, challenge) with the
 * identity @mode names (EPHEMERAL or ACCOUNT; NONE is refused). The sign
 * call starts from an idle on the caller's thread-default context, so the
 * owner has stored the returned attempt before anything can complete. The
 * callback runs at most once, on that context, with either the verified
 * signed JSON and its id or an error; the owner must forget the attempt in
 * it (the attempt releases itself). gh_relay_auth_attempt_drop() cancels
 * the attempt; its callback then never runs. */
typedef struct _GhRelayAuthAttempt GhRelayAuthAttempt;
typedef void (*GhRelayAuthAttemptFunc)(gpointer owner,
                                       const gchar *signed_json,
                                       const gchar *event_id,
                                       const GError *error);
/* ACCOUNT refuses (NULL, G_IO_ERROR_PERMISSION_DENIED) a missing or revoked
 * @account_signer or one bound to another generation than
 * @account_generation; nothing is signed then. EPHEMERAL ignores both. */
GhRelayAuthAttempt *gh_relay_auth_attempt_start(GhRelayAuthMode mode,
                                                GhRelayAuthSigner *account_signer,
                                                guint64 account_generation,
                                                const gchar *relay_url,
                                                const gchar *challenge,
                                                GhRelayAuthAttemptFunc callback,
                                                gpointer owner,
                                                GError **error);
void gh_relay_auth_attempt_drop(GhRelayAuthAttempt *attempt);

G_END_DECLS
#endif
