/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef ___USERS_BIZARRO_DOCUMENTS_PROJECTS_NOSTRC__BUILD_ASAN_NOSTR_GOBJECT_SIGNER_PROXY_H__
#define ___USERS_BIZARRO_DOCUMENTS_PROJECTS_NOSTRC__BUILD_ASAN_NOSTR_GOBJECT_SIGNER_PROXY_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.nostr.Signer */

#define NOSTR_TYPE_ORG_NOSTR_SIGNER (nostr_org_nostr_signer_get_type ())
#define NOSTR_ORG_NOSTR_SIGNER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER, NostrOrgNostrSigner))
#define NOSTR_IS_ORG_NOSTR_SIGNER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER))
#define NOSTR_ORG_NOSTR_SIGNER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER, NostrOrgNostrSignerIface))

struct _NostrOrgNostrSigner;
typedef struct _NostrOrgNostrSigner NostrOrgNostrSigner;
typedef struct _NostrOrgNostrSignerIface NostrOrgNostrSignerIface;

struct _NostrOrgNostrSignerIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_approve_request) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_request_id,
    gboolean arg_decision,
    gboolean arg_remember,
    guint64 arg_ttl_seconds);

  gboolean (*handle_clear_key) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_identity);

  gboolean (*handle_decrypt_zap_event) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_event_json,
    const gchar *arg_current_user);

  gboolean (*handle_get_public_key) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_relays) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_nip04_decrypt) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_ciphertext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user);

  gboolean (*handle_nip04_encrypt) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_plaintext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user);

  gboolean (*handle_nip44_decrypt) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_ciphertext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user);

  gboolean (*handle_nip44_encrypt) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_plaintext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user);

  gboolean (*handle_sign_event) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_event_json,
    const gchar *arg_current_user,
    const gchar *arg_app_id);

  gboolean (*handle_store_key) (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_key,
    const gchar *arg_identity);

  void (*approval_completed) (
    NostrOrgNostrSigner *object,
    const gchar *arg_request_id,
    gboolean arg_decision);

  void (*approval_requested) (
    NostrOrgNostrSigner *object,
    const gchar *arg_app_id,
    const gchar *arg_identity,
    const gchar *arg_kind,
    const gchar *arg_preview,
    const gchar *arg_request_id);

};

GType nostr_org_nostr_signer_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *nostr_org_nostr_signer_interface_info (void);
guint nostr_org_nostr_signer_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void nostr_org_nostr_signer_complete_get_public_key (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *npub);

void nostr_org_nostr_signer_complete_sign_event (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *signature);

void nostr_org_nostr_signer_complete_nip44_encrypt (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *ciphertext);

void nostr_org_nostr_signer_complete_nip44_decrypt (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *plaintext);

void nostr_org_nostr_signer_complete_nip04_encrypt (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *ciphertext);

void nostr_org_nostr_signer_complete_nip04_decrypt (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *plaintext);

void nostr_org_nostr_signer_complete_decrypt_zap_event (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *decrypted_event);

void nostr_org_nostr_signer_complete_get_relays (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    const gchar *relays_json);

void nostr_org_nostr_signer_complete_store_key (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    gboolean ok,
    const gchar *npub);

void nostr_org_nostr_signer_complete_clear_key (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    gboolean ok);

void nostr_org_nostr_signer_complete_approve_request (
    NostrOrgNostrSigner *object,
    GDBusMethodInvocation *invocation,
    gboolean ok);



/* D-Bus signal emissions functions: */
void nostr_org_nostr_signer_emit_approval_requested (
    NostrOrgNostrSigner *object,
    const gchar *arg_app_id,
    const gchar *arg_identity,
    const gchar *arg_kind,
    const gchar *arg_preview,
    const gchar *arg_request_id);

void nostr_org_nostr_signer_emit_approval_completed (
    NostrOrgNostrSigner *object,
    const gchar *arg_request_id,
    gboolean arg_decision);



/* D-Bus method calls: */
void nostr_org_nostr_signer_call_get_public_key (
    NostrOrgNostrSigner *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_get_public_key_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_npub,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_get_public_key_sync (
    NostrOrgNostrSigner *proxy,
    gchar **out_npub,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_sign_event (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_event_json,
    const gchar *arg_current_user,
    const gchar *arg_app_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_sign_event_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_signature,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_sign_event_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_event_json,
    const gchar *arg_current_user,
    const gchar *arg_app_id,
    gchar **out_signature,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_nip44_encrypt (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_plaintext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_nip44_encrypt_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_ciphertext,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_nip44_encrypt_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_plaintext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    gchar **out_ciphertext,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_nip44_decrypt (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_ciphertext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_nip44_decrypt_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_plaintext,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_nip44_decrypt_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_ciphertext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    gchar **out_plaintext,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_nip04_encrypt (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_plaintext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_nip04_encrypt_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_ciphertext,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_nip04_encrypt_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_plaintext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    gchar **out_ciphertext,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_nip04_decrypt (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_ciphertext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_nip04_decrypt_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_plaintext,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_nip04_decrypt_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_ciphertext,
    const gchar *arg_peer_pubkey,
    const gchar *arg_current_user,
    gchar **out_plaintext,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_decrypt_zap_event (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_event_json,
    const gchar *arg_current_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_decrypt_zap_event_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_decrypted_event,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_decrypt_zap_event_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_event_json,
    const gchar *arg_current_user,
    gchar **out_decrypted_event,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_get_relays (
    NostrOrgNostrSigner *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_get_relays_finish (
    NostrOrgNostrSigner *proxy,
    gchar **out_relays_json,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_get_relays_sync (
    NostrOrgNostrSigner *proxy,
    gchar **out_relays_json,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_store_key (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_key,
    const gchar *arg_identity,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_store_key_finish (
    NostrOrgNostrSigner *proxy,
    gboolean *out_ok,
    gchar **out_npub,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_store_key_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_key,
    const gchar *arg_identity,
    gboolean *out_ok,
    gchar **out_npub,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_clear_key (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_identity,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_clear_key_finish (
    NostrOrgNostrSigner *proxy,
    gboolean *out_ok,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_clear_key_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_identity,
    gboolean *out_ok,
    GCancellable *cancellable,
    GError **error);

void nostr_org_nostr_signer_call_approve_request (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_request_id,
    gboolean arg_decision,
    gboolean arg_remember,
    guint64 arg_ttl_seconds,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean nostr_org_nostr_signer_call_approve_request_finish (
    NostrOrgNostrSigner *proxy,
    gboolean *out_ok,
    GAsyncResult *res,
    GError **error);

gboolean nostr_org_nostr_signer_call_approve_request_sync (
    NostrOrgNostrSigner *proxy,
    const gchar *arg_request_id,
    gboolean arg_decision,
    gboolean arg_remember,
    guint64 arg_ttl_seconds,
    gboolean *out_ok,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define NOSTR_TYPE_ORG_NOSTR_SIGNER_PROXY (nostr_org_nostr_signer_proxy_get_type ())
#define NOSTR_ORG_NOSTR_SIGNER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER_PROXY, NostrOrgNostrSignerProxy))
#define NOSTR_ORG_NOSTR_SIGNER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NOSTR_TYPE_ORG_NOSTR_SIGNER_PROXY, NostrOrgNostrSignerProxyClass))
#define NOSTR_ORG_NOSTR_SIGNER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER_PROXY, NostrOrgNostrSignerProxyClass))
#define NOSTR_IS_ORG_NOSTR_SIGNER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER_PROXY))
#define NOSTR_IS_ORG_NOSTR_SIGNER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NOSTR_TYPE_ORG_NOSTR_SIGNER_PROXY))

typedef struct _NostrOrgNostrSignerProxy NostrOrgNostrSignerProxy;
typedef struct _NostrOrgNostrSignerProxyClass NostrOrgNostrSignerProxyClass;
typedef struct _NostrOrgNostrSignerProxyPrivate NostrOrgNostrSignerProxyPrivate;

struct _NostrOrgNostrSignerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  NostrOrgNostrSignerProxyPrivate *priv;
};

struct _NostrOrgNostrSignerProxyClass
{
  GDBusProxyClass parent_class;
};

GType nostr_org_nostr_signer_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NostrOrgNostrSignerProxy, g_object_unref)
#endif

void nostr_org_nostr_signer_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NostrOrgNostrSigner *nostr_org_nostr_signer_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
NostrOrgNostrSigner *nostr_org_nostr_signer_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void nostr_org_nostr_signer_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NostrOrgNostrSigner *nostr_org_nostr_signer_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
NostrOrgNostrSigner *nostr_org_nostr_signer_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define NOSTR_TYPE_ORG_NOSTR_SIGNER_SKELETON (nostr_org_nostr_signer_skeleton_get_type ())
#define NOSTR_ORG_NOSTR_SIGNER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER_SKELETON, NostrOrgNostrSignerSkeleton))
#define NOSTR_ORG_NOSTR_SIGNER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NOSTR_TYPE_ORG_NOSTR_SIGNER_SKELETON, NostrOrgNostrSignerSkeletonClass))
#define NOSTR_ORG_NOSTR_SIGNER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER_SKELETON, NostrOrgNostrSignerSkeletonClass))
#define NOSTR_IS_ORG_NOSTR_SIGNER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NOSTR_TYPE_ORG_NOSTR_SIGNER_SKELETON))
#define NOSTR_IS_ORG_NOSTR_SIGNER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NOSTR_TYPE_ORG_NOSTR_SIGNER_SKELETON))

typedef struct _NostrOrgNostrSignerSkeleton NostrOrgNostrSignerSkeleton;
typedef struct _NostrOrgNostrSignerSkeletonClass NostrOrgNostrSignerSkeletonClass;
typedef struct _NostrOrgNostrSignerSkeletonPrivate NostrOrgNostrSignerSkeletonPrivate;

struct _NostrOrgNostrSignerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  NostrOrgNostrSignerSkeletonPrivate *priv;
};

struct _NostrOrgNostrSignerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType nostr_org_nostr_signer_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NostrOrgNostrSignerSkeleton, g_object_unref)
#endif

NostrOrgNostrSigner *nostr_org_nostr_signer_skeleton_new (void);


G_END_DECLS

#endif /* ___USERS_BIZARRO_DOCUMENTS_PROJECTS_NOSTRC__BUILD_ASAN_NOSTR_GOBJECT_SIGNER_PROXY_H__ */
