/* test_vapi_smoke.c generated by valac 0.56.18, the Vala compiler
 * generated from test_vapi_smoke.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <GNostrGtk-1.0.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

static gint _vala_main (gchar** args,
                 gint args_length1);

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	GType t = 0UL;
	gint _tmp0_ = 0;
	gint result;
	t = nostr_gtk_timeline_view_get_type ();
	if (t == G_TYPE_INVALID) {
		_tmp0_ = 1;
	} else {
		_tmp0_ = 0;
	}
	result = _tmp0_;
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

