/*
 * Code generated by cascadia generate — DO NOT EDIT.
 * Source: registry/event-families.yaml, registry/tags.yaml
 * Generated: reproducible
 *
 * Cascadia Protocol — Canonical constants, metadata, and helpers.
 * Compatible with C99+ and C++11+.
 */

#ifndef CASCADIA_PROTOCOL_H
#define CASCADIA_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ─── Kind Constants ──────────────────────────────────────────────────── */

/** NIP59_GIFT_WRAP — NIP-59 gift wrap transport for encrypted ContextVM payloads. */
#define NIP59_GIFT_WRAP  ((uint16_t)1059)

/** CAS_AUDIT — Audit trail event and attestation. Append-only, immutable record of auditable actions. Independent of request lifecyc... */
#define CAS_AUDIT  ((uint16_t)4903)

/** CAS_WORKER_AD — Compute worker advertisement. Replaceable latest-wins record (one per pubkey) announcing hardware capabilities, avail... */
#define CAS_WORKER_AD  ((uint16_t)10100)

/** CTXVM_SERVER_ANNOUNCEMENT — ContextVM server discovery announcement. */
#define CTXVM_SERVER_ANNOUNCEMENT  ((uint16_t)11316)

/** CTXVM_TOOLS_ANNOUNCEMENT — ContextVM tools discovery announcement. */
#define CTXVM_TOOLS_ANNOUNCEMENT  ((uint16_t)11317)

/** CTXVM_RESOURCES_ANNOUNCEMENT — ContextVM resources discovery announcement. */
#define CTXVM_RESOURCES_ANNOUNCEMENT  ((uint16_t)11318)

/** CTXVM_RESOURCE_TEMPLATES_ANNOUNCEMENT — ContextVM resource templates discovery announcement. */
#define CTXVM_RESOURCE_TEMPLATES_ANNOUNCEMENT  ((uint16_t)11319)

/** CTXVM_PROMPTS_ANNOUNCEMENT — ContextVM prompts discovery announcement. */
#define CTXVM_PROMPTS_ANNOUNCEMENT  ((uint16_t)11320)

/** NIP59_EPHEMERAL_GIFT_WRAP — Ephemeral NIP-59 gift wrap transport for no-persistence ContextVM payloads. */
#define NIP59_EPHEMERAL_GIFT_WRAP  ((uint16_t)21059)

/** CAS_INTENT — ContextVM JSON-RPC 2.0 intent message. Carries all Cascadia command requests, responses, and notifications; normally ... */
#define CAS_INTENT  ((uint16_t)25910)

/** NIP51_TASK_COLLECTION — NIP-51 named list for Task Fabric collections. Uses d-tags prefixed with queue:<id> for work queues and epic:<id> for... */
#define NIP51_TASK_COLLECTION  ((uint16_t)30000)

/** NIP38_USER_STATUS — NIP-38 user status for operational status updates. */
#define NIP38_USER_STATUS  ((uint16_t)30315)

/** CAS_AGENT_HEARTBEAT — Agent lifecycle heartbeat. Addressable latest-wins record signaling agent liveness. Refreshes every 30-120 seconds. C... */
#define CAS_AGENT_HEARTBEAT  ((uint16_t)30316)

/** CAS_AGENT_CAPABILITY — Agent capability descriptor. Addressable latest-wins record describing an agent's tools, models, and operational scop... */
#define CAS_AGENT_CAPABILITY  ((uint16_t)30317)

/** CAS_CP_STATE — Control-plane state projection. Addressable latest-wins record representing the current computed truth of an entity. ... */
#define CAS_CP_STATE  ((uint16_t)30900)

/* ─── Event Form Constants ────────────────────────────────────────────── */

#define CASCADIA_EVENT_FORM_REGULAR      0
#define CASCADIA_EVENT_FORM_REPLACEABLE  1
#define CASCADIA_EVENT_FORM_ADDRESSABLE  2
#define CASCADIA_EVENT_FORM_EPHEMERAL    3

/* ─── Tag Name Constants ──────────────────────────────────────────────── */

#define CASCADIA_TAG_TRIGGERED_BY                     "triggered-by"
#define CASCADIA_TAG_INTENT                           "intent"
#define CASCADIA_TAG_RUN                              "run"
#define CASCADIA_TAG_SESSION                          "session"
#define CASCADIA_TAG_ACP_VERSION                      "acp_version"
#define CASCADIA_TAG_BACKEND                          "backend"
#define CASCADIA_TAG_CAP                              "cap"
#define CASCADIA_TAG_DM_SCHEMES                       "dm_schemes"
#define CASCADIA_TAG_MODEL                            "model"
#define CASCADIA_TAG_RUNTIME                          "runtime"
#define CASCADIA_TAG_SCOPE                            "scope"
#define CASCADIA_TAG_TOOL                             "tool"
#define CASCADIA_TAG_TOOLS                            "tools"
#define CASCADIA_TAG_A                                "a"
#define CASCADIA_TAG_ARTIFACT                         "artifact"
#define CASCADIA_TAG_DOC                              "doc"
#define CASCADIA_TAG_PROJECT                          "project"
#define CASCADIA_TAG_SCHEMA                           "schema"
#define CASCADIA_TAG_SUPERSEDES                       "supersedes"
#define CASCADIA_TAG_TITLE                            "title"
#define CASCADIA_TAG_TYPE                             "type"
#define CASCADIA_TAG_V                                "v"
#define CASCADIA_TAG_WORKFLOW                         "workflow"
#define CASCADIA_TAG_AGENT                            "agent"
#define CASCADIA_TAG_DOMAIN                           "domain"
#define CASCADIA_TAG_ENVIRONMENT                      "environment"
#define CASCADIA_TAG_METHOD                           "method"
#define CASCADIA_TAG_OP                               "op"
#define CASCADIA_TAG_RELEASE                          "release"
#define CASCADIA_TAG_ROUTE                            "route"
#define CASCADIA_TAG_SERVICE                          "service"
#define CASCADIA_TAG_WORKER                           "worker"
#define CASCADIA_TAG_ASSIGNEE                         "assignee"
#define CASCADIA_TAG_DECISION                         "decision"
#define CASCADIA_TAG_DEPENDS_ON                       "depends-on"
#define CASCADIA_TAG_EPIC                             "epic"
#define CASCADIA_TAG_PRIORITY                         "priority"
#define CASCADIA_TAG_STAGE                            "stage"
#define CASCADIA_TAG_STATUS                           "status"
#define CASCADIA_TAG_STEP                             "step"

/* ─── Kind Metadata ───────────────────────────────────────────────────── */

/** Maximum number of required tags for any single kind. */
#define CASCADIA_MAX_REQUIRED_TAGS  3

/** Number of canonical Cascadia kinds. */
#define CASCADIA_KIND_COUNT  15

/** Metadata for a Cascadia event kind. */
typedef struct {
    uint16_t    kind;
    const char *symbol;
    const char *family;
    uint8_t     event_form;   /* 0=regular, 1=replaceable, 2=addressable, 3=ephemeral */
    uint8_t     num_required_tags;
    const char *required_tags[3];
} cascadia_kind_info_t;

/** Table of all canonical Cascadia kinds (defined in cascadia.c). */
extern const cascadia_kind_info_t cascadia_kinds[CASCADIA_KIND_COUNT];

/* ─── Functions ───────────────────────────────────────────────────────── */

/**
 * Look up kind metadata by kind number.
 * Returns NULL if the kind is not a canonical Cascadia kind.
 */
const cascadia_kind_info_t *cascadia_kind_lookup(uint16_t kind);

/**
 * Check whether a kind uses replaceable or addressable semantics.
 * Returns 1 (true) if replaceable/addressable, 0 otherwise.
 */
int cascadia_is_replaceable(uint16_t kind);

#ifdef __cplusplus
} /* extern "C" */

/* ─── C++ Convenience API ─────────────────────────────────────────────── */

namespace cascadia {

/** Compile-time kind constants. */
namespace kind {
    inline constexpr uint16_t Nip59GiftWrap          = 1059;
    inline constexpr uint16_t CasAudit               = 4903;
    inline constexpr uint16_t CasWorkerAD            = 10100;
    inline constexpr uint16_t CtxvmServerAnnouncement = 11316;
    inline constexpr uint16_t CtxvmToolsAnnouncement = 11317;
    inline constexpr uint16_t CtxvmResourcesAnnouncement = 11318;
    inline constexpr uint16_t CtxvmResourceTemplatesAnnouncement = 11319;
    inline constexpr uint16_t CtxvmPromptsAnnouncement = 11320;
    inline constexpr uint16_t Nip59EphemeralGiftWrap = 21059;
    inline constexpr uint16_t CasIntent              = 25910;
    inline constexpr uint16_t Nip51TaskCollection    = 30000;
    inline constexpr uint16_t Nip38UserStatus        = 30315;
    inline constexpr uint16_t CasAgentHeartbeat      = 30316;
    inline constexpr uint16_t CasAgentCapability     = 30317;
    inline constexpr uint16_t CasCPState             = 30900;
} // namespace kind

/** Compile-time tag name constants. */
namespace tag {
    inline constexpr const char *TriggeredBy            = "triggered-by";
    inline constexpr const char *Intent                 = "intent";
    inline constexpr const char *Run                    = "run";
    inline constexpr const char *Session                = "session";
    inline constexpr const char *ACPVersion             = "acp_version";
    inline constexpr const char *Backend                = "backend";
    inline constexpr const char *Cap                    = "cap";
    inline constexpr const char *DMSchemes              = "dm_schemes";
    inline constexpr const char *Model                  = "model";
    inline constexpr const char *Runtime                = "runtime";
    inline constexpr const char *Scope                  = "scope";
    inline constexpr const char *Tool                   = "tool";
    inline constexpr const char *Tools                  = "tools";
    inline constexpr const char *A                      = "a";
    inline constexpr const char *Artifact               = "artifact";
    inline constexpr const char *Doc                    = "doc";
    inline constexpr const char *Project                = "project";
    inline constexpr const char *Schema                 = "schema";
    inline constexpr const char *Supersedes             = "supersedes";
    inline constexpr const char *Title                  = "title";
    inline constexpr const char *Type                   = "type";
    inline constexpr const char *V                      = "v";
    inline constexpr const char *Workflow               = "workflow";
    inline constexpr const char *Agent                  = "agent";
    inline constexpr const char *Domain                 = "domain";
    inline constexpr const char *Environment            = "environment";
    inline constexpr const char *Method                 = "method";
    inline constexpr const char *Op                     = "op";
    inline constexpr const char *Release                = "release";
    inline constexpr const char *Route                  = "route";
    inline constexpr const char *Service                = "service";
    inline constexpr const char *Worker                 = "worker";
    inline constexpr const char *Assignee               = "assignee";
    inline constexpr const char *Decision               = "decision";
    inline constexpr const char *DependsOn              = "depends-on";
    inline constexpr const char *Epic                   = "epic";
    inline constexpr const char *Priority               = "priority";
    inline constexpr const char *Stage                  = "stage";
    inline constexpr const char *Status                 = "status";
    inline constexpr const char *Step                   = "step";
} // namespace tag

/** Look up kind metadata. Returns nullptr if not found. */
inline const cascadia_kind_info_t *kind_lookup(uint16_t k) {
    return cascadia_kind_lookup(k);
}

} // namespace cascadia

#endif /* __cplusplus */

#endif /* CASCADIA_PROTOCOL_H */
