name: gnostr-signer-daemon
base: core22
version: 0.1.0
summary: GNostr Signer Daemon
description: |
  Background daemon for GNostr Signer to handle signing and IPC.

grade: stable
confinement: strict

apps:
  gnostr-signer-daemon:
    command: usr/bin/gnostr-signer-daemon
    daemon: simple
    restart-condition: on-failure
    plugs: [network, network-bind]

parts:
  app:
    plugin: cmake
    source: ../..
    build-packages:
      - build-essential
      - cmake
      - ninja-build
      - pkg-config
      - libjansson-dev
      - libwebsockets-dev
      - libsecret-1-dev
      - libssl-dev
      - libnsync-dev
    stage-packages:
      - libjansson4
      - libwebsockets16
      - libsecret-1-0
      - libssl3
      - libnsync
    override-build: |
      cmake -S $SNAPCRAFT_PROJECT_DIR -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      cmake --build build -j --target gnostr-signer-daemon
      cmake --install build --prefix $SNAPCRAFT_PART_INSTALL/usr
