#ifndef NOSTR_NIP55L_ERROR_H
#define NOSTR_NIP55L_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

enum NostrSignerError {
  NOSTR_SIGNER_OK = 0,
  NOSTR_SIGNER_ERROR_INVALID_JSON = 1,
  NOSTR_SIGNER_ERROR_INVALID_KEY = 2,
  NOSTR_SIGNER_ERROR_UNAUTHORIZED = 3,
  NOSTR_SIGNER_ERROR_PERMISSION_DENIED = 4,
  NOSTR_SIGNER_ERROR_CRYPTO_FAILED = 5,
  NOSTR_SIGNER_ERROR_NOT_FOUND = 6,
  NOSTR_SIGNER_ERROR_BACKEND = 7,
  NOSTR_SIGNER_ERROR_RATE_LIMITED = 8,
  NOSTR_SIGNER_ERROR_INVALID_ARG = 9
};

#ifdef __cplusplus
}
#endif

#endif
