include_guard(GLOBAL)

include(GNUInstallDirs)

# Declare a component's semantic version and generate its public version header.
#
# The cache entries use CMake's conventional <name>_VERSION_* spelling:
#   <name>_VERSION_MAJOR
#   <name>_VERSION_MINOR
#   <name>_VERSION_MICRO
#   <name>_VERSION
function(declare_component_version name major minor micro)
  if("${name}" STREQUAL "")
    message(FATAL_ERROR "declare_component_version requires a component name")
  endif()

  foreach(_part IN ITEMS major minor micro)
    if(NOT "${${_part}}" MATCHES "^[0-9]+$")
      message(FATAL_ERROR
        "declare_component_version(${name} ...): ${_part} must be a non-negative integer")
    endif()
  endforeach()

  set(_version "${major}.${minor}.${micro}")

  set(${name}_VERSION_MAJOR "${major}" CACHE STRING
    "${name} major version" FORCE)
  set(${name}_VERSION_MINOR "${minor}" CACHE STRING
    "${name} minor version" FORCE)
  set(${name}_VERSION_MICRO "${micro}" CACHE STRING
    "${name} micro version" FORCE)
  set(${name}_VERSION "${_version}" CACHE STRING
    "${name} version" FORCE)

  string(MAKE_C_IDENTIFIER "${name}" _version_identifier)
  string(TOUPPER "${_version_identifier}" _version_prefix)

  set(_version_header_dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
  set(_version_header "${_version_header_dir}/${name}-version.h")
  file(MAKE_DIRECTORY "${_version_header_dir}")
  file(WRITE "${_version_header}"
"/* Generated by VersionHelpers.cmake. Do not edit. */
#ifndef ${_version_prefix}_VERSION_H
#define ${_version_prefix}_VERSION_H

#define ${_version_prefix}_VERSION_MAJOR ${major}
#define ${_version_prefix}_VERSION_MINOR ${minor}
#define ${_version_prefix}_VERSION_MICRO ${micro}
#define ${_version_prefix}_VERSION \"${_version}\"

#endif /* ${_version_prefix}_VERSION_H */
")

  set(${name}_VERSION_HEADER "${_version_header}" CACHE INTERNAL
    "${name} generated version header" FORCE)
  set(${name}_VERSION_HEADER_DIR "${_version_header_dir}" CACHE INTERNAL
    "${name} generated version header directory" FORCE)

  if(TARGET "${name}")
    set_target_properties("${name}" PROPERTIES
      VERSION "${_version}"
      COMPONENT_VERSION_HEADER "${_version_header}"
      COMPONENT_VERSION_HEADER_DIR "${_version_header_dir}")
  endif()
endfunction()

# Make a declared component version header part of a target's public interface,
# and (for shared/module libraries that are installed) set VERSION + SOVERSION.
#
# Version lookup precedence for a target `T`:
#   VERSION   ← ${T}_VERSION       (fallback: none — helper is a no-op then)
#   SOVERSION ← ${T}_SOVERSION     (fallback: MAJOR component parsed from VERSION)
#
# Callers whose target name differs from the declared component prefix should
# bridge the values before calling apply_versioning, e.g. for target `nostr`
# declared as component `NOSTR`:
#     set(nostr_VERSION   "${NOSTR_VERSION}")
#     set(nostr_SOVERSION "${NOSTR_VERSION_MAJOR}")
function(apply_versioning target)
  if(NOT ENABLE_COMPONENT_VERSIONING)
    return()
  endif()

  if(NOT TARGET "${target}")
    message(FATAL_ERROR "apply_versioning: target '${target}' does not exist")
  endif()

  get_target_property(_version_header "${target}" COMPONENT_VERSION_HEADER)
  get_target_property(_version_header_dir "${target}" COMPONENT_VERSION_HEADER_DIR)
  get_target_property(_version_header_install_dir "${target}"
    COMPONENT_VERSION_HEADER_INSTALL_DIR)

  if(NOT _version_header OR _version_header MATCHES "-NOTFOUND$")
    set(_version_header_var "${target}_VERSION_HEADER")
    set(_version_header "${${_version_header_var}}")
  endif()
  if(NOT _version_header_dir OR _version_header_dir MATCHES "-NOTFOUND$")
    set(_version_header_dir_var "${target}_VERSION_HEADER_DIR")
    set(_version_header_dir "${${_version_header_dir_var}}")
  endif()

  if(NOT _version_header OR NOT _version_header_dir)
    message(FATAL_ERROR
      "apply_versioning(${target}) requires declare_component_version(${target} ...) first")
  endif()

  set(_version_var "${target}_VERSION")
  set(_soversion_var "${target}_SOVERSION")
  set(_version_value "")
  if(DEFINED ${_version_var})
    set(_version_value "${${_version_var}}")
    set_property(TARGET "${target}" PROPERTY VERSION "${_version_value}")
  endif()

  # SOVERSION: prefer explicit ${target}_SOVERSION, else derive MAJOR from VERSION.
  # Setting SOVERSION on STATIC/OBJECT libs is harmless (CMake ignores it on
  # non-shared artifacts), so we set it unconditionally when a value is known.
  # NOTE: `if(_soversion_value)` would be FALSE for the string "0" (CMake treats
  # the literal 0 as a false boolean), so we check the string length instead --
  # SOVERSION=0 is a valid, common choice for pre-1.0 libraries.
  set(_soversion_value "")
  if(DEFINED ${_soversion_var})
    set(_soversion_value "${${_soversion_var}}")
  elseif(_version_value)
    string(REGEX MATCH "^[0-9]+" _soversion_value "${_version_value}")
  endif()
  string(LENGTH "${_soversion_value}" _soversion_len)
  if(_soversion_len GREATER 0)
    set_property(TARGET "${target}" PROPERTY SOVERSION "${_soversion_value}")
  endif()

  target_include_directories("${target}" PUBLIC
    "$<BUILD_INTERFACE:${_version_header_dir}>"
    "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>")

  if(NOT _version_header_install_dir OR
      _version_header_install_dir MATCHES "-NOTFOUND$")
    set(_version_header_install_dir "${CMAKE_INSTALL_INCLUDEDIR}")
  endif()

  install(FILES "${_version_header}"
    DESTINATION "${_version_header_install_dir}")
endfunction()
