#ifndef NOSTR_NIP57_TYPES_H
#define NOSTR_NIP57_TYPES_H

/**
 * NIP-57: Lightning Zaps - Type Definitions
 *
 * Defines structures for zap requests (kind 9734) and zap receipts (kind 9735).
 */

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Event kinds for NIP-57 */
#define NOSTR_NIP57_KIND_ZAP_REQUEST 9734
#define NOSTR_NIP57_KIND_ZAP_RECEIPT 9735

/**
 * NostrZapRequest:
 *
 * Represents a zap request event (kind 9734).
 * This event is not published to relays but sent to the recipient's
 * LNURL pay callback URL.
 */
typedef struct {
    char **relays;          /* NULL-terminated array of relay URLs */
    size_t relay_count;     /* Number of relays */
    uint64_t amount;        /* Amount in millisats (0 if not specified) */
    char *lnurl;            /* bech32-encoded lnurl pay URL (may be NULL) */
    char *content;          /* Optional message/comment (may be NULL) */
    char *recipient_pubkey; /* Hex-encoded pubkey of recipient (p tag) */
    char *event_id;         /* Hex-encoded event ID being zapped (e tag, may be NULL) */
    char *event_coordinate; /* Event coordinate for addressable events (a tag, may be NULL) */
    char *sender_pubkey;    /* Hex-encoded pubkey of sender (from event pubkey) */
    int64_t created_at;     /* Timestamp */
    int event_kind;         /* Kind of target event (k tag, -1 if not specified) */
} NostrZapRequest;

/**
 * NostrZapReceipt:
 *
 * Represents a zap receipt event (kind 9735).
 * Created by a lightning node when an invoice generated by a zap request is paid.
 */
typedef struct {
    char *bolt11;               /* BOLT11 invoice string */
    char *preimage;             /* Payment preimage (may be NULL) */
    char *description;          /* JSON-encoded zap request */
    char *recipient_pubkey;     /* Hex-encoded pubkey of recipient (p tag) */
    char *sender_pubkey;        /* Hex-encoded pubkey of sender (P tag, may be NULL) */
    char *event_id;             /* Hex-encoded event ID that was zapped (e tag, may be NULL) */
    char *event_coordinate;     /* Event coordinate (a tag, may be NULL) */
    char *provider_pubkey;      /* Pubkey of the LNURL provider (event pubkey) */
    int64_t created_at;         /* Timestamp (usually invoice paid_at) */
    int event_kind;             /* Kind of target event (k tag, -1 if not specified) */
} NostrZapReceipt;

/**
 * NostrLnurlPayInfo:
 *
 * Information from an LNURL-pay endpoint that supports Nostr zaps.
 */
typedef struct {
    char *callback;         /* Callback URL for zap requests */
    char *nostr_pubkey;     /* Hex-encoded pubkey for signing zap receipts */
    uint64_t min_sendable;  /* Minimum amount in millisats */
    uint64_t max_sendable;  /* Maximum amount in millisats */
    bool allows_nostr;      /* Whether endpoint supports NIP-57 */
} NostrLnurlPayInfo;

/**
 * NostrZapSplit:
 *
 * Represents a single recipient in a zap split configuration.
 */
typedef struct {
    char *pubkey;           /* Hex-encoded pubkey of recipient */
    char *relay;            /* Relay URL to fetch recipient metadata */
    uint32_t weight;        /* Weight for split calculation (0 = no weight specified) */
} NostrZapSplit;

/**
 * NostrZapSplitConfig:
 *
 * Zap split configuration parsed from event tags.
 */
typedef struct {
    NostrZapSplit *splits;  /* Array of split recipients */
    size_t count;           /* Number of recipients */
    uint32_t total_weight;  /* Sum of all weights */
} NostrZapSplitConfig;

/**
 * nostr_nip57_zap_request_free:
 * @req: (transfer full) (nullable): zap request to free
 *
 * Frees a zap request and all its contents.
 */
void nostr_nip57_zap_request_free(NostrZapRequest *req);

/**
 * nostr_nip57_zap_receipt_free:
 * @receipt: (transfer full) (nullable): zap receipt to free
 *
 * Frees a zap receipt and all its contents.
 */
void nostr_nip57_zap_receipt_free(NostrZapReceipt *receipt);

/**
 * nostr_nip57_lnurl_pay_info_free:
 * @info: (transfer full) (nullable): lnurl pay info to free
 *
 * Frees LNURL pay info and all its contents.
 */
void nostr_nip57_lnurl_pay_info_free(NostrLnurlPayInfo *info);

/**
 * nostr_nip57_zap_split_config_free:
 * @config: (transfer full) (nullable): split config to free
 *
 * Frees a zap split configuration and all its contents.
 */
void nostr_nip57_zap_split_config_free(NostrZapSplitConfig *config);

#ifdef __cplusplus
}
#endif

#endif /* NOSTR_NIP57_TYPES_H */
