#!/usr/bin/env python3
"""Generate convergence_forks_fixture.h from convergence-forks.json
(nostrc-w1m0, W25 slice N).

The JSON is the authoritative capture (see README.md, "Convergence forks");
this script only re-encodes it as C constants so the C tests need no JSON
parser.  Run from this directory:  python3 gen_convergence_forks_fixture.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
fx = json.loads((HERE / "convergence-forks.json").read_text())


def c_str(value):
    return json.dumps(value)  # a valid C string literal for ASCII JSON/hex


f = fx["forks"]
lines = [
    "/* GENERATED by gen_convergence_forks_fixture.py from convergence-forks.json --",
    " * do not edit.  MDK v0.11.0 (946e0547485c9a2c393c2048ec3a968fd50fb441): forks",
    " * resolved by MDK's own convergence; provenance in README.md.",
    " * SPDX-License-Identifier: MIT */",
    "#ifndef MARMOT_TEST_CONVERGENCE_FORKS_FIXTURE_H",
    "#define MARMOT_TEST_CONVERGENCE_FORKS_FIXTURE_H",
    "",
    "typedef struct {",
    "    const char *name, *kind, *by, *by_account, *event_json;",
    "    unsigned long long epoch_after;",
    "} ForkMdkStep;",
    "",
]
for k in ("alice", "bob", "carol", "observer"):
    lines.append(f"#define N_FORK_{k.upper()} {c_str(f['accounts'][k])}")
p = f["observer_private"]
for name, val in (
    ("KP_MLS_MESSAGE", f["observer_key_package_mls_message"]),
    ("INIT_SK", p["init_key_private"]),
    ("ENC_SK", p["encryption_key_private"]),
    ("SIG_SEED", p["signature_key_private_seed"]),
    ("SIG_PUB", p["signature_key_public"]),
    ("RUMOR_JSON", f["welcome_rumor_json"]),
    ("GROUP_ID", f["group_id"]),
):
    lines.append(f"#define N_FORK_{name} {c_str(val)}")
lines.append("")
lines.append("/* MDK's verdict after settling each fork (every party agreed). */")
for key in ("race", "depth2", "witnessed"):
    v = f["verdicts"][key]
    lines.append(f"#define N_FORK_{key.upper()}_NAME {c_str(v['name'])}")
    lines.append(f"#define N_FORK_{key.upper()}_EPOCH {v['epoch']}ULL")
lines.append(f"#define N_FORK_WITNESSED_HIGHER_KEY {c_str(f['verdicts']['witnessed']['higher_key'])}")
lines += ["", "static const ForkMdkStep N_FORK_STEPS[] = {"]
for s in f["steps"]:
    lines.append(
        f"    {{{c_str(s['name'])}, {c_str(s['kind'])}, {c_str(s['by'])}, "
        f"{c_str(s['by_account'])},\n     {c_str(s['event_json'])}, {s['epoch_after']}ULL}},"
    )
lines += ["};", f"#define N_FORK_STEP_COUNT {len(f['steps'])}", "", "#endif", ""]
(HERE / "convergence_forks_fixture.h").write_text("\n".join(lines))
