#!/usr/bin/env python3
"""Generate adopted_commits_fixture.h from adopted-commits.json
(nostrc-qp24.5.1.3).

The JSON is the authoritative capture (see README.md, "Commits"); this
script only re-encodes it as C constants so the C tests need no JSON parser.
Run from this directory:  python3 gen_adopted_commits_fixture.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
fx = json.loads((HERE / "adopted-commits.json").read_text())


def c_str(value):
    return json.dumps(value)  # a valid C string literal for ASCII JSON/hex


m = fx["mdk_engine"]
o = fx["openmls_forgeries"]
lines = [
    "/* GENERATED by gen_adopted_commits_fixture.py from adopted-commits.json -- do",
    " * not edit.  MDK v0.11.0 (946e0547485c9a2c393c2048ec3a968fd50fb441) and its",
    " * pinned OpenMLS: adopted-profile Commits; provenance in README.md.",
    " * SPDX-License-Identifier: MIT */",
    "#ifndef MARMOT_TEST_ADOPTED_COMMITS_FIXTURE_H",
    "#define MARMOT_TEST_ADOPTED_COMMITS_FIXTURE_H",
    "",
    "typedef struct {",
    "    const char *name, *kind, *by, *by_account, *event_json;",
    "    unsigned long long epoch_after;",
    "} AdoptedMdkStep;",
    "",
    "typedef struct {",
    "    const char *name, *by, *message;",
    "} AdoptedForgery;",
    "",
    "/* mdk_engine: MDK v0.11.0 engines; the observer's KeyPackage keys. */",
]
for k in ("alice", "bob", "carol", "dave", "observer"):
    lines.append(f"#define H_MDK_{k.upper()} {c_str(m['accounts'][k])}")
p = m["observer_private"]
for name, val in (
    ("KP_MLS_MESSAGE", m["observer_key_package_mls_message"]),
    ("KP_REF", m["observer_key_package_ref"]),
    ("INIT_SK", p["init_key_private"]),
    ("ENC_SK", p["encryption_key_private"]),
    ("SIG_SEED", p["signature_key_private_seed"]),
    ("SIG_PUB", p["signature_key_public"]),
    ("RUMOR_JSON", m["welcome_rumor_json"]),
    ("GROUP_ID", m["group_id"]),
    ("NOSTR_GROUP_ID", m["nostr_group_id"]),
    ("ROTATED_NOSTR_GROUP_ID", m["rotated_nostr_group_id"]),
):
    lines.append(f"#define H_MDK_{name} {c_str(val)}")
lines.append(f"#define H_MDK_RELAY_A {c_str(m['relays'][0])}")
lines.append(f"#define H_MDK_RELAY_B {c_str(m['relays'][1])}")
lines.append(f"#define H_MDK_RELAY_C {c_str(m['rotated_relays'][1])}")
lines += ["", "static const AdoptedMdkStep H_MDK_STEPS[] = {"]
for s in m["steps"]:
    lines.append(
        f"    {{{c_str(s['name'])}, {c_str(s['kind'])}, {c_str(s['by'])}, "
        f"{c_str(s['by_account'])},\n     {c_str(s['event_json'])}, {s['epoch_after']}ULL}},"
    )
lines += ["};", f"#define H_MDK_STEP_COUNT {len(m['steps'])}", ""]

lines.append("/* openmls_forgeries: pinned OpenMLS, admins X and W, Y no admin. */")
p = o["observer_private"]
for name, val in (
    ("KP", o["observer_key_package"]),
    ("INIT_SK", p["init_key_private"]),
    ("ENC_SK", p["encryption_key_private"]),
    ("SIG_SEED", p["signature_key_private_seed"]),
    ("SIG_PUB", p["signature_key_public"]),
    ("WELCOME", o["welcome"]),
    ("X", o["creator_account"]),
    ("W", o["w_account"]),
    ("Y", o["y_account"]),
):
    lines.append(f"#define H_OMLS_{name} {c_str(val)}")
lines.append(f"#define H_OMLS_W_LEAF {o['w_leaf']}u")
lines.append(f"#define H_OMLS_Y_LEAF {o['y_leaf']}u")
lines.append(f"#define H_OMLS_O_LEAF {o['o_leaf']}u")
for k, v in o["by_ref"].items():
    lines.append(f"#define H_OMLS_REF_{k.upper()} {c_str(v)}")
lines += ["", "static const AdoptedForgery H_OMLS_COMMITS[] = {"]
for k in sorted(o["commits"]):
    c = o["commits"][k]
    lines.append(f"    {{{c_str(k)}, {c_str(c['by'])},\n     {c_str(c['message'])}}},")
lines += ["};", f"#define H_OMLS_COMMIT_COUNT {len(o['commits'])}", ""]

# A second group that has not enabled lifecycle-v1 (slice H review M1).
lc = o["lifecycle_less"]
lines.append("/* openmls_forgeries.lifecycle_less: creator XL, the observer; 0x800c")
lines.append(" * neither required nor present. */")
p = lc["observer_private"]
for name, val in (
    ("KP", lc["observer_key_package"]),
    ("INIT_SK", p["init_key_private"]),
    ("ENC_SK", p["encryption_key_private"]),
    ("SIG_SEED", p["signature_key_private_seed"]),
    ("SIG_PUB", p["signature_key_public"]),
    ("WELCOME", lc["welcome"]),
    ("XL", lc["creator_account"]),
):
    lines.append(f"#define H_OMLS_LC_{name} {c_str(val)}")
lines += ["", "static const AdoptedForgery H_OMLS_LC_COMMITS[] = {"]
for k in sorted(lc["commits"]):
    c = lc["commits"][k]
    lines.append(f"    {{{c_str(k)}, {c_str(c['by'])},\n     {c_str(c['message'])}}},")
lines += ["};", f"#define H_OMLS_LC_COMMIT_COUNT {len(lc['commits'])}", "", "#endif", ""]
(HERE / "adopted_commits_fixture.h").write_text("\n".join(lines))
print("wrote adopted_commits_fixture.h")
