#!/usr/bin/env python3
"""Generate adopted_fixture.h from adopted-groups.json (nostrc-qp24.5.1).

The JSON is the authoritative capture (see README.md); this script only
re-encodes it as C string constants so the C tests need no JSON parser.
Run from this directory:  python3 gen_adopted_fixture.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
fx = json.loads((HERE / "adopted-groups.json").read_text())


def c_str(value):
    return json.dumps(value)  # a valid C string literal for ASCII JSON/hex


lines = [
    "/* GENERATED by gen_adopted_fixture.py from adopted-groups.json -- do not edit.",
    " * MDK v0.11.0 (946e0547485c9a2c393c2048ec3a968fd50fb441) adopted-profile",
    " * captures; provenance in README.md.  SPDX-License-Identifier: MIT */",
    "#ifndef MARMOT_TEST_ADOPTED_FIXTURE_H",
    "#define MARMOT_TEST_ADOPTED_FIXTURE_H",
    "",
    "typedef struct {",
    "    const char *creator_pub, *joiner_pub, *joiner_secret;",
    "    const char *kp_mls_message, *kp_ref, *kp_event_json;",
    "    const char *init_sk, *enc_sk, *sig_seed, *sig_pub;",
    "    const char *rumor_json, *welcome, *group_id, *group_context, *ratchet_tree;",
    "    const char *nostr_group_id, *relay_a, *relay_b;",
    "    unsigned long long epoch;",
    "} AdoptedMdkFixture;",
    "",
]

for key, name in (("engine_default", "MDK011_ENGINE_DEFAULT"),
                  ("white_noise_app", "MDK011_WHITE_NOISE_APP")):
    s = fx[key]
    p = s["joiner_private"]
    lines.append(f"static const AdoptedMdkFixture {name} = {{")
    for field, val in (
        ("creator_pub", s["creator_account_public"]),
        ("joiner_pub", s["joiner_account_public"]),
        ("joiner_secret", s["joiner_account_secret_test_only"]),
        ("kp_mls_message", s["joiner_key_package_mls_message"]),
        ("kp_ref", s["joiner_key_package_ref"]),
        ("kp_event_json", s["joiner_key_package_event_json"]),
        ("init_sk", p["init_key_private"]),
        ("enc_sk", p["encryption_key_private"]),
        ("sig_seed", p["signature_key_private_seed"]),
        ("sig_pub", p["signature_key_public"]),
        ("rumor_json", s["welcome_rumor_json"]),
        ("welcome", s["welcome_mls_message"]),
        ("group_id", s["group_id"]),
        ("group_context", s["group_context_extensions"]),
        ("ratchet_tree", s["ratchet_tree"]),
        ("nostr_group_id", s["nostr_group_id"]),
        ("relay_a", s["relays"][0]),
        ("relay_b", s["relays"][1]),
    ):
        lines.append(f"    .{field} = {c_str(val)},")
    lines.append(f"    .epoch = {int(s['epoch'])}ULL,")
    lines.append("};")
    lines.append("")

neg = fx["openmls_negatives"]
p = neg["joiner_private"]
lines += [
    "/* OpenMLS-built (MDK's pinned fork) Welcomes to one joiner: a valid",
    " * control and one per refusal class. */",
    f"static const char OMLS_NEG_JOINER_KP[] = {c_str(neg['joiner_key_package'])};",
    f"static const char OMLS_NEG_INIT_SK[] = {c_str(p['init_key_private'])};",
    f"static const char OMLS_NEG_ENC_SK[] = {c_str(p['encryption_key_private'])};",
    f"static const char OMLS_NEG_SIG_SEED[] = {c_str(p['signature_key_private_seed'])};",
    f"static const char OMLS_NEG_SIG_PUB[] = {c_str(p['signature_key_public'])};",
]
for variant, hexw in sorted(neg["welcomes"].items()):
    lines.append(f"static const char OMLS_NEG_WELCOME_{variant}[] = {c_str(hexw)};")
c = neg["commits"]
lines += [
    "/* A valid adopted OpenMLS group with the same joiner, and three",
    " * PublicMessage Commits from its joined epoch adding a third member. */",
    f"static const char OMLS_COMMITS_WELCOME[] = {c_str(c['welcome'])};",
    f"static const char OMLS_COMMIT_ADD_VALID[] = {c_str(c['add_valid'])};",
    f"static const char OMLS_COMMIT_ADD_WITHOUT_PROOF[] = {c_str(c['add_without_proof'])};",
    f"static const char OMLS_COMMIT_ADD_MISSING_COMPONENT[] = {c_str(c['add_missing_component'])};",
]
lines += ["", "#endif /* MARMOT_TEST_ADOPTED_FIXTURE_H */", ""]
(HERE / "adopted_fixture.h").write_text("\n".join(lines))
print("wrote", HERE / "adopted_fixture.h")
