name: Backpressure Matrix Nightly

on:
  schedule:
    - cron: "17 6 * * *"  # daily at 06:17 UTC
  workflow_dispatch:

jobs:
  nightly-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build pkg-config \
            libssl-dev libglib2.0-dev libgirepository1.0-dev libcjson-dev \
            python3 python3-pip

      - name: Configure (CMake)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j2

      - name: Run matrix (consume-us=2000)
        run: |
          python3 scripts/run_bp_matrix.py \
            --caps "1,2,4,8,16,32,64" \
            --duration-ms 30000 \
            --burst 128 \
            --sleep-us 500 \
            --interval-ms 200 \
            --modes try,block \
            --consume-us 2000 \
            --outdir build/bp_matrix_cu2000
          python3 scripts/aggregate_bp_matrix.py \
            --base build/bp_matrix_cu2000 \
            --out-prefix build/bp_matrix_cu2000/summary
          python3 scripts/generate_bp_report.py \
            --base build/bp_matrix_cu2000 \
            --out build/bp_matrix_cu2000/REPORT.md

      - name: Run matrix (consume-us=5000)
        run: |
          python3 scripts/run_bp_matrix.py \
            --caps "1,2,4,8,16,32,64" \
            --duration-ms 30000 \
            --burst 128 \
            --sleep-us 500 \
            --interval-ms 200 \
            --modes try,block \
            --consume-us 5000 \
            --outdir build/bp_matrix_cu5000
          python3 scripts/aggregate_bp_matrix.py \
            --base build/bp_matrix_cu5000 \
            --out-prefix build/bp_matrix_cu5000/summary
          python3 scripts/generate_bp_report.py \
            --base build/bp_matrix_cu5000 \
            --out build/bp_matrix_cu5000/REPORT.md

      - name: Run matrix (consume-us=10000)
        run: |
          python3 scripts/run_bp_matrix.py \
            --caps "1,2,4,8,16,32,64" \
            --duration-ms 30000 \
            --burst 128 \
            --sleep-us 500 \
            --interval-ms 200 \
            --modes try,block \
            --consume-us 10000 \
            --outdir build/bp_matrix_cu10000
          python3 scripts/aggregate_bp_matrix.py \
            --base build/bp_matrix_cu10000 \
            --out-prefix build/bp_matrix_cu10000/summary
          python3 scripts/generate_bp_report.py \
            --base build/bp_matrix_cu10000 \
            --out build/bp_matrix_cu10000/REPORT.md

      - name: Generate top-level nightly summary
        run: |
          python3 scripts/generate_nightly_bp_summary.py \
            --root build \
            --out build/bp_matrix_nightly/INDEX.md

      - name: Upload nightly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bp-matrix-nightly-artifacts
          path: |
            build/bp_matrix_cu2000
            build/bp_matrix_cu5000
            build/bp_matrix_cu10000
            build/bp_matrix_nightly
